#!/usr/bin/env bash
set -eu

apt-get update
apt-get install -y curl qemu-user-static binfmt-support jq moreutils

curl https://download.docker.com/linux/static/stable/x86_64/docker-18.09.1.tgz | \
  tar xvz docker/docker

mkdir -p ~/.docker
jq --null-input  --arg experimental enabled '. + {experimental: $experimental}' | \
sponge ~/.docker/config.json
